### ISSUE TITLE
Can't choose gtk3 theme in tweak-tool

### ISSUE THREAD

**Issue by mlutz** [hdni/Phosphene#1]
Maybe you can help me. I put the repository in /usr/share/themes and i can choose shell-theme etc in tweak tool, but when i want to choose the gtk+ theme there is no Phosphene to choose. Do i miss something?
I'm using Ubuntu 10.3

Greetings
espo

**Comment by hdni** [comment]
This is probably because there's no GTK 2 theme included in the directory (because I haven't made one yet), while the Tweak Tool sets both GTK 2 and GTK 3 themes at the same time. You can just take any gtk-2.0 directory from any theme you want to use (for example, Adwaita) and copy it in the Phosphene directory; that should work.

**Comment by mlutz** [comment]
Thanks! That was the Problem
