### ISSUE TITLE
Icon theme

### ISSUE THREAD

**Issue by moisturizer** [hdni/Phosphene#16]
Is your mod of the eOS icon theme available for download somewhere? 
I quite like the look of those folder icons.

**Comment by evanpurkhiser** [comment]
According to the post [here](http://pixelfuckers.org/submissions/2212), the icons are still in a state of incompletness. Hopefully we will see them released soon though, they look great!

> I’ll have to think whether I want to finish the icon theme or not; right now it’s quite incomplete, because GNU/Linux icon themes are a lot of work. I’ll probably end up releasing them soon though. Thank you.

**Comment by moisturizer** [comment]
I wouldn't mind the set being incomplete. I'd be happy with just the folder icons.

**Comment by hdni** [comment]
Okay, [here it is](http://a.pomf.se/wklrhv.gz).
It's missing a lot of stuff, but the main reason I didn't release it before is because the places icons — the ones in the home folder, with the symbolic icons on them, for Music, Pictures, etc., etc. — weren't and aren't finished. If you keep your icons at the default size in there, you shouldn't notice. 
It inherits from Faience, which in turn inherits from Faenza, so make sure you have both those sets.
