### ISSUE TITLE
Software groups doesn`t open

### ISSUE THREAD

**Issue by mohsen-rashidi** [hdni/Phosphene#18]
The Utilities and Sundry sections which should be open while clicking on them don`t open when Phosphene selected as Shell theme. For example when you click on Utilities, system stucks for a few seconds and you won`t see what are in them

**Comment by Zeklandia** [comment]
Works fine on my laptop, with Phosphene set as the theme, too.

**Comment by hdni** [comment]
Works for me, too. Make sure you're using the right version of the theme according to your Gnome version (see #9).
Since it sounds like user error, I'll close the issue.
![screenshot from 2014-01-05 09 46 41](https://f.cloud.github.com/assets/3179152/1846766/4521f5da-7618-11e3-8626-0e3c49a350fd.png)
