### ISSUE TITLE
Maximized Windows Lose Titlebar

### ISSUE THREAD

**Issue by Zeklandia** [hdni/Phosphene#20]
This makes it rather difficult to manage maximized windows.

**Comment by hdni** [comment]
You'll have noticed that the theme in general is meant to be used with keyboard shortcuts; that's why, for instance, the window controls are so small and the title bar disappears on maximized windows. I've gotten used to Gnome's shortcuts because they're well defined and efficient. They're fairly intuitive by default, and you can modify them in the Keyboard settings, but if you haven't:
- Super + up to maximize
- Super + down to restore
- Super + left/right to snap left/right
- Super + click to drag
- Super + right-click to resize
- Alt-f4 to close

So my answer to your issue is that the title bars are mainly there to be pretty, though they can be useful in some situations. That's how Phosphene is; another example is the Firefox tabs (#17). It's part of the design (**_it's not a bug, it's a feature!!!**_).
