### ISSUE TITLE
Various Controls Too Small

### ISSUE THREAD

**Issue by Zeklandia** [hdni/Phosphene#21]
The following are too small to be operated easily:
- scrollbars
- drop-down application menus (in GNOME Shell)
- window controls (exit, resize, minimize)
- the header of seekbars
- window title bars

**Comment by hdni** [comment]
- Scrollbars are small because they're only, in this case, an indicator of where you are on a page. You can use your mouse/touchpad and PageUp/Down, Home/End on the keyboard to navigate quickly;
- I don't see how the drop-down menus are too small to be used with a mouse, but if you find that they are, it's for an aesthetic reason, as you'll hear me repeat throughout;
- Windows controls & window title bars — see #20;
- I'm not sure what you mean by "the headers of seekbars", but in the Shell seekbars can be interacted with by clicking anywhere on their container (what becomes blue when hovered), and GTK 3 seekbars all have a fairly big slider.

Maybe the theme simply isn't for you, and I say this without a hint of condescension in my mind. Our workflows may be different; I think Phosphene, as you've pointed out, is pretty revealing of when I tend to use the mouse or when I use the keyboard to interact with elements, and your use case seems to be different. I hope you'll understand that these aren't things I'll change since I'm comfortable with them. _Either you're with me, or you're with the the terrorists._

**Comment by Zeklandia** [comment]
I guess it would be easier if:
a. this weren't a laptop
b. it didn't have a smaller screen
c. that smaller screen weren't 1080p

Everything is incredibly tiny on my laptop screen, so I guess most of these are just from that (except the scrolling).

Also, I figured out the seekbar heads don't matter.
