### ISSUE TITLE
Window title won't change

### ISSUE THREAD

**Issue by gandl** [hdni/Phosphene#5]
Hi,

i installed your theme and in works fine apart from the window titles. They stay with the standard theme.
I'm running Ubuntu Gnome 13.10 Beta. (Gnome 3.8)

Also, which themes are you using for your folder icons?

Greetings

**Comment by hdni** [comment]
I can't really help you here, I don't use Ubuntu. Maybe the problem is on their end, since it's a beta, I have no idea. Good luck figuring it out!
The icon set is a custom mod of Elementary, I haven't released them because I've been to lazy to at least finish the folders at all sizes. They may be out there one day, or not... who knows.

**Comment by ghost** [comment]
To fix follow this steps:
1. Choose default themes
2. Transfer your themes from ~/.themes to ~/.local/share/themes
3. Restart GNOME Shell: Alt+F2, type r and press Enter
4. Now window titles should work

**Comment by gandl** [comment]
Thanks for your help, but this won't work either.

//Edit, i tried a little bit of moving/removing themes and now it works. Thanks alot. :)
