### ISSUE TITLE
Menus and Shell Bar Display Incorrectly

### ISSUE THREAD

**Issue by jorbas** [hdni/Phosphene#9]
In both Phosphene and Fleche the menus in some applications and also the bar at the top of Gnome Shell do not display correctly. Flex displays correctly so I think it might have something to do with Fleche and Phosphene being Gnome 3.10 compatible. The problem with this though is that I was previously using Fleche on 3.8 just fine until I wiped my drive. Perhaps I had downloaded a 3.8 version of Fleche before, I'm not sure.

Update: Okay, the menus in applications such as Sublime Text and Firefox work correctly if the theme is placed in /usr/share/themes, but not if they are placed in ~/.local/share/themes. The problem with then main Gnome Shell bar remains though.

![fleche_menus](https://f.cloud.github.com/assets/1732497/1648640/40983d84-59ae-11e3-85be-9631f103009d.png)
![fleche_menus_2](https://f.cloud.github.com/assets/1732497/1648642/409904f8-59ae-11e3-9918-453abec4e6ef.png)

**Comment by hdni** [comment]
> I think it might have something to do with Fleche and Phosphene being Gnome 3.10 compatible.

You don't seem to be using 3.10 (according to your user menu), so that's definitely the cause. I had to modify a lot of stuff to get the Shell theme up to date, and it's not really backwards compatible, as you can tell.
You should try using the 3.8 versions of the themes, which are still on GitHub:
https://github.com/hdni/Fleche/tree/c6b71e087bd0bdf9a1814df9a1e40677a7ad43e3
https://github.com/hdni/Phosphene/tree/190338736be98c914d53fb789140930584b019ea

The /usr/share/themes and ~/.local/share/themes problem is something that I know of, but as far as I know I can't do anything about it. I recommend always putting themes in /usr/share/themes.

**Comment by jorbas** [comment]
Perfect, those work just fine.
